/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package studentgrade.app;

import studentgrade.list.LinkedList;

import static studentgrade.utilities.StringUtils.join;
import static studentgrade.utilities.StringUtils.split;
import static studentgrade.app.MessageUtils.getMessage;

//import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        //System.out.println(WordUtils.capitalize(result));
        System.out.println(result);
    }
}
