/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    id("io.quarkus") apply false
    id("io.freefair.lombok") apply false
    id("org.kordamp.gradle.jandex") apply false
}

