/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.0.2/userguide/multi_project_builds.html
 */
pluginManagement {
    val quarkusPluginVersion: String by settings
    val quarkusPluginId: String by settings
    val lombokPluginId: String by settings
    val lombokPluginVersion: String by settings
    val palantirDockerRunPluginId: String by settings
    val palantirVersion: String by settings
    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        id(quarkusPluginId) version quarkusPluginVersion
        id(lombokPluginId) version lombokPluginVersion
        id(palantirDockerRunPluginId) version palantirVersion
    }
}

rootProject.name = "studentgrade"
include("app", "list", "utilities")
