/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("studentgrade.java-application-conventions")
    id("io.quarkus")
    id("io.freefair.lombok")
    id("com.palantir.docker-run")
}

dependencies {
//    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))

    implementation("io.quarkus:quarkus-hibernate-reactive")
    implementation("io.quarkus:quarkus-reactive-mysql-client")

    testImplementation("io.quarkus:quarkus-junit5-mockito")
    testImplementation("org.mockito:mockito-junit-jupiter")
    testImplementation("org.testcontainers:testcontainers")
    testImplementation("org.testcontainers:junit-jupiter")

}

application {
    // Define the main class for the application.
    mainClass.set("studentgrade.app.App")
}

dockerRun {
    //https://github.com/palantir/gradle-docker/issues/248
    name="DBServerx"
    image="mariadb:10.6.3"
    daemonize=true
    ports("3306:3306")
    env(mapOf(
        "MYSQL_ROOT_PASSWORD" to "quarkus_test",
        "MYSQL_DATABASE" to "quarkus_test",
        "MYSQL_USER" to "quarkus_test",
        "MYSQL_PASSWORD" to "quarkus_test"
    ))   
}