-- INSERT INTO result(schoolId, studentId, maths, art, chemistry, createId, createTime) VALUES ('abc', 'st1', 'PASS','FAIL','PASS','hnum',now());
-- INSERT INTO result(schoolId, studentId, maths, art, chemistry, createId, createTime) VALUES ('abc', 'st2', 'PASS','PASS','PASS','hnum',now());
-- INSERT INTO result(schoolId, studentId, maths, art, chemistry, createId, createTime) VALUES ('abc', 'st3', 'FAIL','FAIL','PASS','hnum',now());
-- INSERT INTO result(schoolId, studentId, maths, art, chemistry, createId, createTime) VALUES ('abc', 'st4', 'FAIL','PASS','PASS','hnum',now());
-- INSERT INTO result(schoolId, studentId, maths, art, chemistry, createId, createTime) VALUES ('abc', 'st5', 'FAIL','FAIL','FAIL','hnum',now());
-- INSERT INTO result(schoolId, studentId, maths, art, chemistry, createId, createTime) VALUES ('xyz', 'st1', 'PASS','PASS','PASS','hnum',now());
-- INSERT INTO result(schoolId, studentId, maths, art, chemistry, createId, createTime) VALUES ('xyz', 'st2', 'PASS','PASS','PASS','hnum',now());
-- INSERT INTO result(schoolId, studentId, maths, art, chemistry, createId, createTime) VALUES ('xyz', 'st3', 'FAIL','FAIL','FAIL','hnum',now());
