-- INSERT INTO result(schoolId, studentId, maths, art, chemistry) VALUES ('abc', 'st1', 'PASS','FAIL','PASS');
-- INSERT INTO result(schoolId, studentId, maths, art, chemistry) VALUES ('abc', 'st2', 'PASS','PASS','PASS');
-- INSERT INTO result(schoolId, studentId, maths, art, chemistry) VALUES ('abc', 'st3', 'FAIL','FAIL','PASS');
-- INSERT INTO result(schoolId, studentId, maths, art, chemistry) VALUES ('abc', 'st4', 'FAIL','PASS','PASS');
-- INSERT INTO result(schoolId, studentId, maths, art, chemistry) VALUES ('abc', 'st5', 'FAIL','FAIL','FAIL');
-- INSERT INTO result(schoolId, studentId, maths, art, chemistry) VALUES ('xyz', 'st1', 'PASS','PASS','PASS');
-- INSERT INTO result(schoolId, studentId, maths, art, chemistry) VALUES ('xyz', 'st2', 'PASS','PASS','PASS');
-- INSERT INTO result(schoolId, studentId, maths, art, chemistry) VALUES ('xyz', 'st3', 'FAIL','FAIL','FAIL');
