/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    java
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

val quarkusPlatformGroupId: String by project
val quarkusPlatformArtifactId: String by project
val quarkusPlatformVersion: String by project

dependencies {
//    constraints {
        // Define dependency versions as constraints
//    }

    implementation(enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}"))
    implementation("io.quarkus:quarkus-grpc")

    implementation("org.jboss.logmanager:log4j2-jboss-logmanager")

    // Use JUnit Jupiter API for testing.
    testImplementation("io.quarkus:quarkus-junit5")
    // testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.1")

    // Use JUnit Jupiter Engine for testing.
    //testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
}

tasks.test {
    failFast = true
	systemProperty("java.util.logging.manager", "org.jboss.logmanager.LogManager")
    
    // Use junit platform for unit tests.
    useJUnitPlatform()
}
