/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    id("io.quarkus")
    id("io.freefair.lombok") 
    id("org.kordamp.gradle.jandex")
    id("com.palantir.docker-run")
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://maven.pkg.github.com/drsarutobi8/*")
    }
}

val quarkusPlatformGroupId: String by project
val quarkusPlatformArtifactId: String by project
val quarkusPlatformVersion: String by project

dependencies {
    implementation(project(":studentApi"))
    implementation(project(":resultApi"))
    implementation(project(":resultService"))

    compileOnly("org.projectlombok:lombok:1.18.20")

    implementation(enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}"))
    implementation("io.quarkus:quarkus-grpc")
    implementation("io.quarkus:quarkus-hibernate-reactive-panache")
    //implementation("io.quarkus:quarkus-hibernate-reactive")
    implementation("io.quarkus:quarkus-reactive-mysql-client")
    implementation("io.quarkus:quarkus-resteasy")
    implementation("io.quarkus:quarkus-resteasy-mutiny")

    //implementation("io.quarkus:quarkus-jdbc-h2")
    //implementation("io.quarkus:quarkus-hibernate-orm-panache")
    //runtimeOnly("io.quarkus:quarkus-hibernate-orm-deployment")

    testImplementation("io.quarkus:quarkus-junit5")
    testImplementation("io.rest-assured:rest-assured")
    testImplementation("org.awaitility:awaitility")
    testImplementation("org.assertj:assertj-core")
}

group = "org.acme"
version = "1.0.0-SNAPSHOT"
description = "grpc-plain-text-quickstart"
java.sourceCompatibility = JavaVersion.VERSION_11

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

dockerRun {
    name = "mariadb"
    image = "mariadb:10.6.3"
    daemonize = true
    clean = true
    ports("3306:3306")
    env(
        mapOf(
            "MYSQL_ROOT_PASSWORD" to "quarkus_test",
            "MYSQL_DATABASE" to "quarkus_test",
            "MYSQL_USER" to "quarkus_test",
            "MYSQL_PASSWORD" to "quarkus_test"
        )
    )
}