INSERT INTO student(schoolId, studentId, name, age, gender, createId, createTime) VALUES ('abc', 'st1', 'John',17,'MALE','hnum',now());
INSERT INTO student(schoolId, studentId, name, age, gender, createId, createTime) VALUES ('abc', 'st2', 'Jenny',16,'FEMALE','hnum',now());
INSERT INTO student(schoolId, studentId, name, age, gender, createId, createTime) VALUES ('abc', 'st3', 'Azam',16,'MALE','hnum',now());
INSERT INTO student(schoolId, studentId, name, age, gender, createId, createTime) VALUES ('abc', 'st4', 'Lisa',16,'FEMALE','hnum',now());
INSERT INTO student(schoolId, studentId, name, age, gender, createId, createTime) VALUES ('abc', 'st5', 'Shehani',16,'FEMALE','hnum',now());
INSERT INTO student(schoolId, studentId, name, age, gender, createId, createTime) VALUES ('xyz', 'st1', 'Mike',17,'MALE','hnum',now());
INSERT INTO student(schoolId, studentId, name, age, gender, createId, createTime) VALUES ('xyz', 'st2', 'Janine',16,'FEMALE','hnum',now());
INSERT INTO student(schoolId, studentId, name, age, gender, createId, createTime) VALUES ('xyz', 'st3', 'Aaron',17,'MALE','hnum',now());
-- INSERT INTO result(schoolId, studentId, maths, art, chemistry, createId, createTime) VALUES ('abc', 'st1', 'PASS','FAIL','PASS','hnum',now());
-- INSERT INTO result(schoolId, studentId, maths, art, chemistry, createId, createTime) VALUES ('abc', 'st2', 'PASS','PASS','PASS','hnum',now());
-- INSERT INTO result(schoolId, studentId, maths, art, chemistry, createId, createTime) VALUES ('abc', 'st3', 'FAIL','FAIL','PASS','hnum',now());
-- INSERT INTO result(schoolId, studentId, maths, art, chemistry, createId, createTime) VALUES ('abc', 'st4', 'FAIL','PASS','PASS','hnum',now());
-- INSERT INTO result(schoolId, studentId, maths, art, chemistry, createId, createTime) VALUES ('abc', 'st5', 'FAIL','FAIL','FAIL','hnum',now());
-- INSERT INTO result(schoolId, studentId, maths, art, chemistry, createId, createTime) VALUES ('xyz', 'st1', 'PASS','PASS','PASS','hnum',now());
-- INSERT INTO result(schoolId, studentId, maths, art, chemistry, createId, createTime) VALUES ('xyz', 'st2', 'PASS','PASS','PASS','hnum',now());
-- INSERT INTO result(schoolId, studentId, maths, art, chemistry, createId, createTime) VALUES ('xyz', 'st3', 'FAIL','FAIL','FAIL','hnum',now());